#!/bin/bash

# Trims the images generated by generate_plots.sage

for file in ../plots/*.png
do
    echo $file
    convert -trim $file $file

#     if [[ $file == 'plots/abs_jsun_geq1.png' ]]
#     then
#         convert $file -channel RGB -negate -set colorspace Gray -separate -average $file
#     fi
done
